# -*- coding: utf-8 AA-*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.




from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QThread, pyqtSignal, pyqtSlot, QModelIndex, QObject, QPoint
from PyQt5.QtGui import QPixmap, QPainter, QColor, QFont, QImage, QIcon
from pyqtgraph import PlotWidget, GraphicsLayoutWidget
from PyQt5.QtWidgets import*

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 1000)
        self.colors = [(183, 101, 224), (93, 131, 212), (49, 205, 222), (36, 214, 75), (214, 125, 36) ,(230, 78, 192), (209, 84, 65), (0, 184, 245)]
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        #self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1500, 900))
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidget.setMinimumSize(QtCore.QSize(1000,0)) 
        
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        #self.tab1.setMinimumSize(QtCore.QSize(1500,0)) 
        self.tab1.setMaximumSize(QtCore.QSize(2000,16777215)) 
        
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.tab2.setMaximumSize(QtCore.QSize(2000,16777215)) 

        self.tabWidget.addTab(self.tab1, "Main")
        self.tabWidget.addTab(self.tab2, "Pressure")

        #MainWindow.setCentralWidget(self.centralwidget)
        MainWindow.setCentralWidget(self.tabWidget)
        # Vertical layout for tab1
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab1)
        self.verticalLayout.setObjectName("verticalLayout")
        

        self.mainsetup_1 = QtWidgets.QHBoxLayout()
        self.mainsetup_1.setObjectName("setupLayout")
       
        
        self.refreshButton = QtWidgets.QPushButton(self.tab1)
        self.refreshButton.setObjectName("refreshButton")
        #self.refreshButton.setMinimumSize(QtCore.QSize(200, 16777215)) 
        self.refreshButton.setText("Refresh Port")
        self.mainsetup_1.addWidget(self.refreshButton)

        self.intervalInput = QtWidgets.QLineEdit(self.tab1)
        self.intervalInput.setObjectName("intervalInput")
        self.intervalInput.setPlaceholderText("Logging Interval (s)")
        self.intervalInput.setMaximumSize(QtCore.QSize(200, 16777215)) 
        self.mainsetup_1.addWidget(self.intervalInput)
        
        self.LogBothButton = QtWidgets.QPushButton(self.tab1)
        self.LogBothButton.setObjectName("LogBothButton")
        self.LogBothButton.setText("Log Both")
        #self.LogBothButton.setMinimumSize(QtCore.QSize(200, 16777215)) 
        self.mainsetup_1.addWidget(self.LogBothButton)

        self.startStopButton = QtWidgets.QPushButton(self.tab1)
        #self.startStopButton.setMinimumSize(QtCore.QSize(200, 16777215))
        self.startStopButton.setObjectName("startStopButton")
        self.mainsetup_1.addWidget(self.startStopButton)

        self.verticalLayout.addLayout(self.mainsetup_1)

        # HUMIDITY
        # Sub Hum 1
        self.HumHLayout_1 = QtWidgets.QHBoxLayout()
        self.HumHLayout_1.setObjectName("HumHLayout")
        
        self.HumPortBox = QtWidgets.QComboBox(self.tab1)
        self.HumPortBox.setObjectName("HumPortBox")
        self.HumHLayout_1.addWidget(self.HumPortBox)
        
        self.HumBaudBox = QtWidgets.QComboBox(self.tab1)
        self.HumBaudBox.setObjectName("HumBaudBox")
        self.HumBaudBox.addItems(["9600", "4800", "9600","19200", "38400", "57600", "115200"])
        self.HumHLayout_1.addWidget(self.HumBaudBox)

        self.HumsaveDirectoryButton = QtWidgets.QPushButton(self.tab1)
        self.HumsaveDirectoryButton.setObjectName("HumsaveDirectoryButton")
        self.HumsaveDirectoryButton.setText("File Directory")
        self.HumHLayout_1.addWidget(self.HumsaveDirectoryButton)

        self.HumLogButton = QtWidgets.QPushButton(self.tab1)
        self.HumLogButton.setObjectName("HumLogButton")
        self.HumLogButton.setText("Log Humidity")
        self.HumHLayout_1.addWidget(self.HumLogButton)
        
        self.HumfileLabel = QtWidgets.QLabel(self.tab1)
        self.HumfileLabel.setObjectName("HumfileLabel")
        self.HumHLayout_1.addWidget(self.HumfileLabel)
        
        self.verticalLayout.addLayout(self.HumHLayout_1)

        # Sub Hum 2
        self.HumHLayout_2 = QtWidgets.QHBoxLayout()
        self.HumHLayout_2.setObjectName("HumHLayout_2")

        self.HumVLayout_2_1 = QtWidgets.QVBoxLayout()
        self.HumVLayout_2_1.setObjectName("HumVLayout_2_1")
        self.HumHLayout_2.addLayout(self.HumVLayout_2_1)

        self.Humlabel4 = QtWidgets.QLabel(self.tab1)
        self.Humlabel4.setObjectName("Humlabel4")
        self.Humlabel4.setText(f"AH: --")
        self.Humlabel4.setStyleSheet(f"font-weight: bold; font-size: 14px; color: magenta ; background-color: white; border: 1px solid black;")
        self.Humlabel4.setFixedSize(100, 40)
        self.HumVLayout_2_1.addWidget(self.Humlabel4)


        self.Humlabel1 = QtWidgets.QLabel(self.tab1)
        self.Humlabel1.setObjectName("Humlabel2")
        self.Humlabel1.setText(f"RH: --")
        self.Humlabel1.setStyleSheet(f"font-weight: bold; font-size: 14px; color: rgb(190, 17, 17); background-color: white; border: 1px solid black;")
        self.Humlabel1.setFixedSize(100, 40)
        self.HumVLayout_2_1.addWidget(self.Humlabel1)

        self.Humlabel2 = QtWidgets.QLabel(self.tab1)
        self.Humlabel2.setObjectName("Humlabel2")
        self.Humlabel2.setText(f"Tmp: --")
        self.Humlabel2.setStyleSheet(f"font-weight: bold; font-size: 14px; color: rgb(0, 184, 245) ; background-color: white; border: 1px solid black;")
        self.Humlabel2.setFixedSize(100, 40)
        self.HumVLayout_2_1.addWidget(self.Humlabel2)

        self.Humlabel3 = QtWidgets.QLabel(self.tab1)
        self.Humlabel3.setObjectName("Humlabel2")
        self.Humlabel3.setText(f"Dew: --")
        self.Humlabel3.setStyleSheet(f"font-weight: bold; font-size: 14px; color: black ; background-color: white; border: 1px solid black;")
        self.Humlabel3.setFixedSize(100, 40)
        self.HumVLayout_2_1.addWidget(self.Humlabel3)

        self.HumclearButton = QtWidgets.QPushButton(self.tab1)
        #self.HumclearButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.HumclearButton.setObjectName("HumclearButton")
        self.HumclearButton.setText("Clear")
        self.HumVLayout_2_1.addWidget(self.HumclearButton)
        
        self.graphics_layout = GraphicsLayoutWidget(self.centralwidget)
        self.graphics_layout.setMinimumSize(QtCore.QSize(0,300))
        #self.graphics_layout.setMaximumSize(QtCore.QSize(750,16777215))
        self.HumHLayout_2.addWidget(self.graphics_layout)
        
        self.HumPlotWidget2 = PlotWidget(self.tab1)
        self.HumPlotWidget2.setMinimumSize(QtCore.QSize(0,300))
        #self.HumPlotWidget2.setMaximumSize(QtCore.QSize(750,16777215))
        self.HumPlotWidget2.setObjectName("HumPlotWidget2")
        self.HumHLayout_2.addWidget(self.HumPlotWidget2)
        
        self.verticalLayout.addLayout(self.HumHLayout_2)
        
        # For temperature
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        
        self.TempPortBox = QtWidgets.QComboBox(self.tab1)
        self.TempPortBox.setObjectName("TempPortBox")
        self.horizontalLayout_2.addWidget(self.TempPortBox)
        
        self.TempBaudBox = QtWidgets.QComboBox(self.tab1)
        self.TempBaudBox.setObjectName("TempBaudBox")
        self.TempBaudBox.addItems(["38400", "4800", "9600","19200", "57600", "115200"])
        self.horizontalLayout_2.addWidget(self.TempBaudBox)
        
        self.saveDirectoryButton = QtWidgets.QPushButton(self.tab1)
        self.saveDirectoryButton.setObjectName("saveDirectoryButton")
        self.saveDirectoryButton.setText("File Directory")
        self.horizontalLayout_2.addWidget(self.saveDirectoryButton)

        self.TempLogButton = QtWidgets.QPushButton(self.tab1)
        self.TempLogButton.setObjectName("TempLogButton")
        self.TempLogButton.setText("Log Temperature")
        self.horizontalLayout_2.addWidget(self.TempLogButton)
        
        self.fileLabel = QtWidgets.QLabel(self.tab1)
        self.fileLabel.setObjectName("fileLabel")
        self.horizontalLayout_2.addWidget(self.fileLabel)

        self.verticalLayout.addLayout(self.horizontalLayout_2)
        
        # Sub Temp 2
        self.TempHLayout_2 = QtWidgets.QHBoxLayout()
        self.TempHLayout_2.setObjectName("TempHLayout_2")

        self.TempVLayout_2_1 = QtWidgets.QVBoxLayout()
        self.TempVLayout_2_1.setObjectName("TempVLayout_2_1")
        self.TempHLayout_2.addLayout(self.TempVLayout_2_1)

        #diagram
        height = 560
        width = int(height/2.3)
        self.DiagramWidget = QtWidgets.QWidget(self.tab1)
        self.DiagramWidget.setFixedSize(width, height)
        self.DiagramLayout = QtWidgets.QStackedLayout(self.DiagramWidget)
        self.imageLabel = QtWidgets.QLabel()
        pixmap = QPixmap("diagram.png")
        pixmap = pixmap.scaled(width, height)
        self.imageLabel.setPixmap(pixmap)
        self.imageLabel.setGeometry(0, 0, width, height)

        self.DiagramLayout.addWidget(self.imageLabel)
        self.labels = []
        for i in range(8):
            label = QtWidgets.QLabel(self.DiagramWidget)
            label.setText(f"T{i+1}")
            label.setStyleSheet(f"font-weight: bold; font-size: 14px; color: white ; background-color: rgb{self.colors[i]}; border: 1px solid black;")
            label.setFixedSize(70, 30)
            #label.move(i*20, i*20)
            self.labels.append(label)
            
        self.labels[0].move(int(0.02*width),int(0.88*height))  #T1
        self.labels[1].move(int(0.14*width),int(0.80*height))  #T2
        self.labels[2].move(int(0.24*width),int(0.71*height))  #T3
        self.labels[3].move(int(0.64*width),int(0.55*height)) #T4
        self.labels[4].move(int(0.20*width),int(0.46*height))  #T5
        self.labels[5].move(int(0.66*width),int(0.41*height)) #T6
        self.labels[6].move(int(0.64*width),int(0.28*height)) #T7
        self.labels[7].move(int(0.26*width),int(0.1*height))   #T8
        self.TempHLayout_2.addWidget(self.DiagramWidget)



        self.TempPlotWidget = PlotWidget(self.tab1)
        #self.TempPlotWidget.setMinimumSize(QtCore.QSize(1500,560))
        #self.TempPlotWidget.setMaximumSize(QtCore.QSize(1500,16777215))
        self.TempPlotWidget.setObjectName("TempPlotWidget")
        self.TempHLayout_2.addWidget(self.TempPlotWidget)

        self.verticalLayout.addLayout(self.TempHLayout_2)
        
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkboxes = []
        for i in range(8):
            self.checkBox = QtWidgets.QCheckBox()
            self.checkBox.setMaximumSize(QtCore.QSize(60,30))
            self.checkBox.setMinimumSize(QtCore.QSize(40,0))
            self.checkBox.setObjectName(f"T{i+1}")
            self.checkBox.setChecked(True)
            self.verticalLayout_2.addWidget(self.checkBox)
            self.checkBox.setStyleSheet(f"font-weight: bold; font-size: 14px; color: white; background-color: rgb{self.colors[i]}; border: 1px solid black;")
            self.checkboxes.append(self.checkBox)
       


        #temp clear button
        self.clearButton = QtWidgets.QPushButton(self.tab1)
        self.clearButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.clearButton.setObjectName("TempclearButton")
        self.clearButton.setText("Clear")
        self.verticalLayout_2.addWidget(self.clearButton)


        self.TempHLayout_2.addLayout(self.verticalLayout_2)



        ###TAB2###
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        #main setup 
        self.mainsetup_2 = QtWidgets.QHBoxLayout()
        self.mainsetup_2.setObjectName("setupLayout")

        self.Presslabel = QtWidgets.QLabel(self.DiagramWidget)
        self.Presslabel.setText("P: -- psi")
        self.Presslabel.setStyleSheet(f"font-weight: bold; font-size: 14px; color: black; background-color: rgb{(152, 245, 249)}; border: 1px solid black;")
        self.Presslabel.setMinimumSize(140, 30)
        self.mainsetup_2.addWidget(self.Presslabel)

        self.PressclearButton = QtWidgets.QPushButton(self.tab2)
        self.PressclearButton.setObjectName("PressclearButton")
        self.PressclearButton.setText("Clear Plot")
        #self.PressclearButton.setMinimumSize(QtCore.QSize(200, 16777215)) 
        self.mainsetup_2.addWidget(self.PressclearButton)

        self.PressPortBox = QtWidgets.QComboBox(self.tab2)
        self.PressPortBox.setObjectName("PressPortBox")
        self.mainsetup_2.addWidget(self.PressPortBox)

        self.refreshButton_2 = QtWidgets.QPushButton(self.tab2)
        self.refreshButton_2.setObjectName("refreshButton")
        #self.refreshButton_2.setMinimumSize(QtCore.QSize(200, 16777215)) 
        self.refreshButton_2.setText("Refresh Port")
        self.mainsetup_2.addWidget(self.refreshButton_2)

        self.PressBaudBox = QtWidgets.QComboBox(self.tab2)
        self.PressBaudBox.setObjectName("PressBaudBox")
        self.PressBaudBox.addItems(["9600", "4800","19200", "38400", "57600", "115200"])
        self.mainsetup_2.addWidget(self.PressBaudBox)
        
        self.PresssaveDirectoryButton = QtWidgets.QPushButton(self.tab2)
        self.PresssaveDirectoryButton.setObjectName("PresssaveDirectoryButton")
        self.PresssaveDirectoryButton.setText("File Directory")
        self.mainsetup_2.addWidget(self.PresssaveDirectoryButton)

        self.intervalInput_2 = QtWidgets.QLineEdit(self.tab2)
        self.intervalInput_2.setObjectName("intervalInput")
        self.intervalInput_2.setPlaceholderText("Logging Interval (s)")
        self.intervalInput_2.setMaximumSize(QtCore.QSize(200, 16777215)) 
        self.mainsetup_2.addWidget(self.intervalInput_2)
        
        self.PressLogButton = QtWidgets.QPushButton(self.tab2)
        self.PressLogButton.setObjectName("LogBothButton")
        self.PressLogButton.setText("Log Pressure")
        #self.PressLogButton.setMinimumSize(QtCore.QSize(200, 16777215)) 
        self.mainsetup_2.addWidget(self.PressLogButton)



        self.startStopButton_2 = QtWidgets.QPushButton(self.tab2)
        #self.startStopButton_2.setMinimumSize(QtCore.QSize(200, 16777215))
        self.startStopButton_2.setObjectName("startStopButton")
        self.startStopButton_2.setText("Start/Stop")
        self.mainsetup_2.addWidget(self.startStopButton_2)

        self.PressfileLabel = QtWidgets.QLabel(self.tab2)
        self.PressfileLabel.setObjectName("PressfileLabel")
        self.mainsetup_2.addWidget(self.PressfileLabel)

        self.verticalLayout_2.addLayout(self.mainsetup_2)


        
        self.PressPlotWidget = PlotWidget(self.tab2)
        self.PressPlotWidget.setBackground("w")
        self.PressPlotWidget.setObjectName("PressPlotWidget")

        self.verticalLayout_2.addWidget(self.PressPlotWidget)
        
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Temperature and Humidity Monitor"))

        for i in range(8):
            self.checkboxes[i].setText(_translate("MainWindow",f"T{i+1}"))
            self.labels[i].setText(_translate("MainWindow", f"T{i+1}"))

        self.startStopButton.setText(_translate("MainWindow", "Start/Stop"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
